version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-socketio
    versions:
    - 5.0.4
    - 5.1.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: uvicorn
    versions:
    - 0.13.3
  - dependency-name: pymongo
    versions:
    - 3.11.2
